### ISSUE TITLE
Latest version not working on psvita tv

### ISSUE THREAD

**Issue by cloudstrife999** [theheroGAC/Auto-Installer-vpk#1]
Hi,
As soon it loads up, it gives an error "attempt to call global 'onAppinstall' ( a nil value)

Please have a look, maybe the new usb plugin causing some issues??

**Comment by theheroGAC** [comment]
sorry,fix the problem https://github.com/theheroGAC/Autovpk/releases/download/1.02/Autovpk.vpk

**Comment by cloudstrife999** [comment]
hey thanks. Luckily i tried out the previous release. That worked. Just saw u updated the vpk.

Will try that out..
